<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>OrderFlow.Messaging</AssemblyName>
    <RootNamespace>OrderFlow.Messaging</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OrderFlow.Contracts/OrderFlow.Contracts.csproj" />
    <PackageReference Include="DotPulsar" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
  </ItemGroup>
</Project>
