pid /tmp/nginx.pid;

events {}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 5000;
        location / {
            set $backend http://web:8080;
            proxy_pass $backend;
        }
    }

    server {
        listen 5001;
        location / {
            set $backend http://orders-api:8080;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 5002;
        location / {
            set $backend http://inventory-api:8080;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    server {
        listen 5003;
        location / {
            set $backend http://payments-api:8080;
            proxy_pass $backend;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
